export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_SINGLE_CHARACTER = "GET_SINGLE_CHARACTER";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const END_API_CALL = "END_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
